#!/usr/bin/env bash
#print "To infinity and beyond" indefinitely, with a sleep 2,
#print a message on SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done