#!/usr/bin/env bash
#displays numbers from 1 to 100
#display fizz when number is multiple of 3
#display buzz when number is multiple of 5
#display fizzbuzz when number is multiple of 3 and 5

counter=1

while [ $counter -le 100 ]
do
    if (( counter % 3 == 0 && count % 5 == 0 ))
    then
    echo "FizzBuzz"
    elif (( counter % 3 == 0 ))
    then
    echo "Fizz"
    elif (( counter % 5 == 0 ))
    then
    echo "Buzz"
    else
    echo "$counter"
    fi
    (( counter++ ))
done
