#!/usr/bin/env bash
#loops from 1-10, displays various messages on luck, otherwise Best School

counter=0

while [ $counter -ne 10 ]
do
    if [ $counter -eq 3 ]
    then
    echo "bad luck"
    elif [ $count -eq 8 ]
    then
    echo "good luck"
    else
    echo "Best School"
    fi
    (( counter++ ))
done