#!/usr/bin/env bash
#Display the content of the current directory
#Display in a list format
#Only the part of the name after the first dash is displayed

list=$(ls)
for i in $list; do
 echo "$i" | cut -d '-' -f2
done